name: CI-CD André Trials

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          echo installing dependencies using Bun
          bun install

      - name: running unit tests
        run: |
          echo Running unit tests using Vitest
          bun test
