name: CI-CD André Trials

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo debugging info
        run: echo Starting the build

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
